#!/bin/bash

# 定义要执行的命令
command="cd .."
command1="make project2 >>result.txt"
command2="echo '==============================================================================================================='>>result.txt"
# 定义循环次数
num_iterations=500

# 使用for循环多次执行命令
eval "$command"
for i in $(seq 1 $num_iterations)
do
    #echo "执行命令: $command"
    # 在这里可以替换为你要执行的具体命令，比如使用$command执行某个命令
     eval "$command1"
     eval "$command2"
done
